parameters:
    karma.annotation_handler.route.class: 'ThinFrame\Karma\AnnotationHandler\RouteHandler'
services:
    karma.annotation_handler.route:
        class: '%karma.annotation_handler.route.class%'
        arguments: ['@karma.router']
        tags:
            - { name: 'annotations.handler' }