services:
    karma.listener.commander:
        class: 'ThinFrame\Karma\Listener\CommanderListener'
        arguments: ['@cli.commander','@cli.arguments_container']
        tags:
            - { name: 'events.listener' }

    karma.listener.output_buffer:
        class: 'ThinFrame\Karma\Listener\OutputBufferListener'
        tags:
            - { name: 'events.listener' }

    karma.listener.quiet_listener:
        class: 'ThinFrame\Karma\Listener\QuietOutputListener'
        tags:
            - { name: 'events.listener' }

    karma.listener.plain_text:
        class: 'ThinFrame\Karma\Listener\PlainTextOutputListener'
        arguments: ['@cli.shortcodes_processor']
        tags:
            - { name: 'events.listener' }

    karma.listener.controllers:
        class: 'ThinFrame\Karma\Listener\ControllersListener'
        tags:
            - { name: 'events.listener' }

    karma.listener.routes_loader:
        class: 'ThinFrame\Karma\Listener\RoutesLoaderListener'
        arguments: ['@karma.router','@annotations.processor']
        tags:
            - { name: 'events.listener' }

    karma.listener.request:
        class: 'ThinFrame\Karma\Listener\RequestListener'
        arguments: ['@karma.router','@karma.route_collection']
        tags:
            - { name: 'events.listener' }

    karma.listener.error:
        class: 'ThinFrame\Karma\Listener\ErrorListener'
        tags:
            - { name: 'events.listener' }

    karma.listener.assets_resolver:
        class: 'ThinFrame\Karma\Listener\AssetsResolverListener'
        arguments: ['@server.react.event_loop']
        tags:
            - { name: 'events.listener' }

    karma.listener.whoops:
        class: 'ThinFrame\Karma\Listener\WhoopsListener'
        arguments: ['@karma.whoops','%environment%']
        tags:
            - { name: 'events.listener' }

    karma.listener.assets:
        class: 'ThinFrame\Karma\Listener\AssetsListener'
        arguments: ['@karma.manager.assets','%karma.paths.root%','%karma.paths.assets%']
        tags:
            - { name: 'events.listener' }