services:
    karma.manager.server:
        class: 'ThinFrame\Karma\Manager\ServerManager'
        arguments: ['@server']

    karma.route_collection:
        class: 'Symfony\Component\Routing\RouteCollection'

    karma.router:
        class: 'ThinFrame\Karma\Controller\Router'
        arguments: ['@karma.route_collection']

    karma.logger.file_handler:
        class: 'Monolog\Handler\StreamHandler'
        arguments: ['%karma.paths.logs%/%environment%.log',100]