services:
    karma.manager.server:
        class: 'ThinFrame\Karma\Manager\ServerManager'
        arguments: ['@server']

    karma.manager.assets:
        class: 'ThinFrame\Karma\Manager\AssetsManager'

    karma.route_collection:
        class: 'Symfony\Component\Routing\RouteCollection'

    karma.router:
        class: 'ThinFrame\Karma\Controller\Router'
        arguments: ['@karma.route_collection']

    karma.whoops:
        class: 'Whoops\Run'
        calls:
            - ['pushHandler',['@karma.whoops.handler']]

    karma.whoops.handler:
        class: 'Whoops\Handler\PrettyPageHandler'
        calls:
            - [handleUnconditionally,[true]]

    karma.logger.file_handler:
        class: 'Monolog\Handler\StreamHandler'
        arguments: ['%karma.paths.logs%/%environment%.log',100]

    karma.logger.memory_peak_usage_processor:
        class: 'Monolog\Processor\MemoryPeakUsageProcessor'

    karma.logger.memory_usage_processor:
        class: 'Monolog\Processor\MemoryUsageProcessor'